# Created by: fabrice.barconniere@ac-dijon.fr
# $FreeBSD$

PORTNAME=	amon
PORTVERSION=	3.0
PORTREVISION=	1
CATEGORIES=	eole
MASTER_SITES=	http://barco.eole.lan/

MAINTAINER=	eole@ac-dijon.fr
COMMENT=	All you need to brand OPNsense for EOLE

LICENSE=        CeCILL-2
LICENSE_NAME=   CONTRAT DE LICENCE DE LOGICIEL LIBRE CeCILL
LICENSE_FILE=   ${FILESDIR}/LICENSE.txt
LICENSE_PERMS=  dist-mirror dist-sell pkg-mirror pkg-sell auto-accept

.include <bsd.port.mk>
